variables:
  GIT_STRATEGY: fetch
  GIT_SSL_NO_VERIFY: "true"
  GIT_LFS_SKIP_SMUDGE: 1

stages:
  - build
  - tests
  - Data_ingestion
        
image_build:
  stage: build
  image: docker:stable
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN http://$CI_REGISTRY
  script: |
    CI_COMMIT_SHA_7=$(echo $CI_COMMIT_SHA | cut -c1-7)
    docker build --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA_7 .
    docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA_7

syntax_check:
  stage: tests
  image: python:3.8
  before_script:
    - pip install flake8
  script:
    - flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
pytests:
  stage: tests
  image: python:3.8
  before_script:
    - pip install -r requirements.txt
  script:
    - pytest tests

Data_update:
  stage: Data_ingestion
  image: 
    name: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA_7
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN http://$CI_REGISTRY
  rules:
    - if: $CI_PIPELINE_REF == "Data_ingestion"
  script:
    - echo "$CI_PIPELINE_REF"

